routes:
- ["geral/produtos/", "ListarProdutos"]
- ["produtos/op/", "ListarOrdemProducao"]
- ["estoque/movestoque/", "ListarMovimentos"]
- ["produtos/nfconsultar/", "ListarNF"]
- ["produtos/pedido/", "ListarPedidos"]  
